const actions = {
  GET_NOTIFICATION: "GET_NOTIFICATION",
  GET_NOTIFICATION_SUCCESS: "GET_NOTIFICATION_SUCCESS",
  GET_NOTIFICATION_FAILURE: "GET_NOTIFICATION_FAILURE",
  SET_NOTIFICATION: "SET_NOTIFICATION",
  SET_NOTIFICATION_SUCCESS: "SET_NOTIFICATION_SUCCESS",
  SET_NOTIFICATION_FAILURE: "SET_NOTIFICATION_FAILURE",
};

export default actions;
