const actions = {
    POST_PARTNERS: 'POST_PARTNERS',
    GET_ADMIN_PARTNERS_LIST: 'GET_ADMIN_PARTNERS_LIST',
    PARTNERS_LIST_RESPONSE: 'PARTNERS_LIST_RESPONSE',
    GET_PARTNERS: 'GET_PARTNERS',
    PARTNERS_RESPONSE: 'PARTNERS_RESPONSE',
    CALL_LOADER: 'CALL_LOADER',
    DELETE_PARTNERS: 'DELETE_PARTNERS',
    GET_ALL_CITY_LIST_PARTNERS : 'GET_ALL_CITY_LIST_PARTNERS',
    GET_ALL_CITY_LIST_SUCCESS_PARTNERS : 'GET_ALL_CITY_LIST_SUCCESS_PARTNERS',
    GET_ALL_CITY_LIST_FAILURE_PARTNERS : 'GET_ALL_CITY_LIST_FAILURE_PARTNERS',
    ACCEPT_REQ : 'ACCEPT_REQ',
    ACCEPT_REQ_SUCCESS : 'ACCEPT_REQ_SUCCESS',
    ACCEPT_REQ_FAILURE : 'ACCEPT_REQ_FAILURE'
}

export default actions;