const actions = {
    GET_LOGIN_DATA: 'GET_LOGIN_DATA',
    GET_LOGIN_DATA_RESPONSE: 'GET_LOGIN_DATA_RESPONSE',
    SET_AUTHORIZATION: 'SET_AUTHORIZATION',
    SHOW_FORGOT_PASSWORD: 'SHOW_FORGOT_PASSWORD',
    CLEAR_AUTHORIZATION: 'CLEAR_AUTHORIZATION',
    GET_USERS: 'GET_USERS',
    GET_USERS_RESPONSE: 'GET_USERS_RESPONSE',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    FORGOT_PASSWORD_RESPONSE: 'FORGOT_PASSWORD_RESPONSE',
    USER_LOGOUT: 'USER_LOGOUT',
    GET_LANGUAGES: 'GET_LANGUAGES',
    GET_LANGUAGE_RESPONSE: 'GET_LANGUAGE_RESPONSE',
    GET_ADMIN_NOTIFY_COUNT: 'GET_ADMIN_NOTIFY_COUNT',
    GET_ADMIN_NOTIFY_COUNT_RESPONSE: 'GET_ADMIN_NOTIFY_COUNT_RESPONSE',
    GET_ADMIN_NOTIFICATIONS: 'GET_ADMIN_NOTIFICATIONS',
    GET_ADMIN_NOTIFICATIONS_RESPONSE: 'GET_ADMIN_NOTIFICATIONS_RESPONSE',
    REST_ADMIN_NOTIFICATION: 'REST_ADMIN_NOTIFICATION',
    REST_ADMIN_NOTIFICATION_RESPONSE: 'REST_ADMIN_NOTIFICATION_RESPONSE'
}

export default actions;
