const actions = {
   GET_DASHBOARD_COUNT: "GET_DASHBOARD_COUNT",
   GET_VENDOR_DASHBOARD_COUNT: "GET_VENDOR_DASHBOARD_COUNT",
   GET_DASHBOARD_COUNT_SUCCESS: "GET_DASHBOARD_COUNT_SUCCESS",
   GET_DASHBOARD_COUNT_FAIL: "GET_DASHBOARD_COUNT_FAIL"
    
}

export default actions;