const actions = {
    GET_ADMIN_RATING_LIST: 'GET_ADMIN_RATING_LIST',
    GET_ADMIN_RATING_LIST_SUCCESS: 'GET_ADMIN_RATING_LIST_SUCCESS',
    GET_ADMIN_RATING_LIST_FAILURE: 'GET_ADMIN_RATING_LIST_FAILURE',
    SET_ADMIN_RATING_CURRENT_PAGE: 'SET_ADMIN_RATING_CURRENT_PAGE',
    SET_ADMIN_RATING_PAGE_SIZE: 'SET_ADMIN_RATING_PAGE_SIZE',
    SET_ADMIN_RATING_FILTERS: 'SET_ADMIN_RATING_FILTERS',
};

export default actions;