const actions = {
    EDIT_PROFILE: 'EDIT_PROFILE',
    EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
    EDIT_PROFILE_FAILURE: 'EDIT_PROFILE_FAILURE',
    SET_EDIT_PROFILE_SUCCESS: 'SET_EDIT_PROFILE_SUCCESS',
    UPLOAD_IMAGE: 'UPLOAD_IMAGE',
    UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS',
    UPLOAD_IMAGE_FAILURE: 'UPLOAD_IMAGE_FAILURE',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',
    SET_UPDATE_PASSWORD_SUCCESS: 'SET_UPDATE_PASSWORD_SUCCESS'
};

export default actions;